### ISSUE TITLE
.progress-bar css class is overriding default bootstrap classes

### ISSUE THREAD

**Issue by simong-hs** [loresoft/LoreSoft.Blazor.Controls#79]
The .progress-bar css class (line 654 BlazorControls.css) is over-riding the default bootstrap .progress-bar class, resulting in all other bootstrap progress bars appearing in strange positions with incorrect heights.

the specific problem is the position: fixed and height: 3px.

Would it be possible to make this class more specific (or rename it), and isolate it to only affect the components contained in this library?

**Comment by pwelter34** [comment]
fixed in v6.2.0
